import React from "react";
import {
  IconShoppingCart,
  IconDiamond,
  IconCalendarEvent,
  IconShirt,
  IconClipboardListFilled,
  IconTruckDelivery,
  IconPaw,
  IconBook2,
  IconScissors,
  IconLanguage,
  IconMusic,
  IconCoffee,
  IconPhoto,
  IconRazor,
  IconUsersGroup,
  IconPlane,
  IconFileCv,
  IconBrain,
  IconLamp,
  IconBrandSuperhuman,
  IconReceipt2,
  IconArtboard,
  IconPalette,
  IconBrush,
  IconHeartbeat,
  IconStethoscope,
  IconScale,
  IconUser,
  IconHeart,
  IconLayoutDashboard,
  IconShoppingBag,
  IconLink,
  IconCamera,
  IconBook,
  IconGoGame,
  IconCpu,
  IconBriefcase,
  IconNews,
} from "@tabler/icons-react";
import { useTranslation } from "next-i18next";

const getSolutions = (t: ReturnType<typeof useTranslation>["t"]) => [
  {
    key: "ecommerce",
    category: t("solutions.ecommerce.title"),
    description: t("solutions.ecommerce.description"),
    price: "2,000",
    discounted: "1,600",
    icon: <IconShoppingCart size={32} />,
  },
  {
    key: "wedding_planners",
    category: t("solutions.wedding_planners.title"),
    description: t("solutions.wedding_planners.description"),
    price: "1,800",
    discounted: "1,400",
    icon: <IconDiamond size={32} />,
  },
  {
    key: "event_organizers",
    category: t("solutions.event_organizers.title"),
    description: t("solutions.event_organizers.description"),
    price: "1,600",
    discounted: "1,300",
    icon: <IconCalendarEvent size={32} />,
  },
  {
    key: "fashion_brands",
    category: t("solutions.fashion_brands.title"),
    description: t("solutions.fashion_brands.description"),
    price: "1,900",
    discounted: "1,500",
    icon: <IconShirt size={32} />,
  },
  {
    key: "makeup_artists",
    category: t("solutions.makeup_artists.title"),
    description: t("solutions.makeup_artists.description"),
    price: "950",
    discounted: "750",
    icon: <IconClipboardListFilled size={32} />,
  },
  {
    key: "delivery_services",
    category: t("solutions.delivery_services.title"),
    description: t("solutions.delivery_services.description"),
    price: "1,600",
    discounted: "1,300",
    icon: <IconTruckDelivery size={32} />,
  },
  {
    key: "pet_care",
    category: t("solutions.pet_care.title"),
    description: t("solutions.pet_care.description"),
    price: "1,100",
    discounted: "900",
    icon: <IconPaw size={32} />,
  },
  {
    key: "bookstores",
    category: t("solutions.bookstores.title"),
    description: t("solutions.bookstores.description"),
    price: "1,100",
    discounted: "900",
    icon: <IconBook2 size={32} />,
  },
  {
    key: "handmade_crafts",
    category: t("solutions.handmade_crafts.title"),
    description: t("solutions.handmade_crafts.description"),
    price: "800",
    discounted: "600",
    icon: <IconScissors size={32} />,
  },
  {
    key: "language_centers",
    category: t("solutions.language_centers.title"),
    description: t("solutions.language_centers.description"),
    price: "1,300",
    discounted: "1,000",
    icon: <IconLanguage size={32} />,
  },
  {
    key: "music_teachers",
    category: t("solutions.music_teachers.title"),
    description: t("solutions.music_teachers.description"),
    price: "1,000",
    discounted: "800",
    icon: <IconMusic size={32} />,
  },
  {
    key: "coffee_shops",
    category: t("solutions.coffee_shops.title"),
    description: t("solutions.coffee_shops.description"),
    price: "1,400",
    discounted: "1,100",
    icon: <IconCoffee size={32} />,
  },
  {
    key: "photobooths",
    category: t("solutions.photobooths.title"),
    description: t("solutions.photobooths.description"),
    price: "1,200",
    discounted: "950",
    icon: <IconPhoto size={32} />,
  },
  {
    key: "barbers",
    category: t("solutions.barbers.title"),
    description: t("solutions.barbers.description"),
    price: "900",
    discounted: "700",
    icon: <IconRazor size={32} />,
  },
  {
    key: "recruiting_agencies",
    category: t("solutions.recruiting_agencies.title"),
    description: t("solutions.recruiting_agencies.description"),
    price: "1,500",
    discounted: "1,200",
    icon: <IconUsersGroup size={32} />,
  },
  {
    key: "travel_agencies",
    category: t("solutions.travel_agencies.title"),
    description: t("solutions.travel_agencies.description"),
    price: "1,900",
    discounted: "1,500",
    icon: <IconPlane size={32} />,
  },
  {
    key: "resume_builders",
    category: t("solutions.resume_builders.title"),
    description: t("solutions.resume_builders.description"),
    price: "500",
    discounted: "400",
    icon: <IconFileCv size={32} />,
  },
  {
    key: "mental_health",
    category: t("solutions.mental_health.title"),
    description: t("solutions.mental_health.description"),
    price: "1,300",
    discounted: "1,000",
    icon: <IconBrain size={32} />,
  },
  {
    key: "home_decor",
    category: t("solutions.home_decor.title"),
    description: t("solutions.home_decor.description"),
    price: "1,100",
    discounted: "900",
    icon: <IconLamp size={32} />,
  },
  {
    key: "baby_stores",
    category: t("solutions.baby_stores.title"),
    description: t("solutions.baby_stores.description"),
    price: "950",
    discounted: "750",
    icon: <IconBrandSuperhuman size={32} />,
  },
  {
    key: "accountants",
    category: t("solutions.accountants.title"),
    description: t("solutions.accountants.description"),
    price: "1,400",
    discounted: "1,100",
    icon: <IconReceipt2 size={32} />,
  },
  {
    key: "restaurant",
    category: t("solutions.restaurant.title"),
    description: t("solutions.restaurant.description"),
    price: "1,800",
    discounted: "1,400",
    icon: <IconArtboard size={32} />,
  },
  {
    key: "real_estate",
    category: t("solutions.real_estate.title"),
    description: t("solutions.real_estate.description"),
    price: "1,600",
    discounted: "1,300",
    icon: <IconPalette size={32} />,
  },
  {
    key: "car_rentals",
    category: t("solutions.car_rentals.title"),
    description: t("solutions.car_rentals.description"),
    price: "1,600",
    discounted: "1,300",
    icon: <IconBrush size={32} />,
  },
  {
    key: "gyms",
    category: t("solutions.gyms.title"),
    description: t("solutions.gyms.description"),
    price: "1,300",
    discounted: "1,000",
    icon: <IconHeartbeat size={32} />,
  },
  {
    key: "medical_clinics",
    category: t("solutions.medical_clinics.title"),
    description: t("solutions.medical_clinics.description"),
    price: "1,800",
    discounted: "1,400",
    icon: <IconStethoscope size={32} />,
  },
  {
    key: "law_firms",
    category: t("solutions.law_firms.title"),
    description: t("solutions.law_firms.description"),
    price: "1,300",
    discounted: "1,000",
    icon: <IconScale size={32} />,
  },
  {
    key: "freelancers",
    category: t("solutions.freelancers.title"),
    description: t("solutions.freelancers.description"),
    price: "700",
    discounted: "500",
    icon: <IconUser size={32} />,
  },
  {
    key: "ngos",
    category: t("solutions.ngos.title"),
    description: t("solutions.ngos.description"),
    price: "1,300",
    discounted: "1,000",
    icon: <IconHeart size={32} />,
  },
  {
    key: "digital_agencies",
    category: t("solutions.digital_agencies.title"),
    description: t("solutions.digital_agencies.description"),
    price: "1,300",
    discounted: "1,000",
    icon: <IconLayoutDashboard size={32} />,
  },
  {
    key: "local_shops",
    category: t("solutions.local_shops.title"),
    description: t("solutions.local_shops.description"),
    price: "700",
    discounted: "500",
    icon: <IconShoppingBag size={32} />,
  },
  {
    key: "influencers",
    category: t("solutions.influencers.title"),
    description: t("solutions.influencers.description"),
    price: "500",
    discounted: "400",
    icon: <IconLink size={32} />,
  },
  {
    key: "photographers",
    category: t("solutions.photographers.title"),
    description: t("solutions.photographers.description"),
    price: "1,000",
    discounted: "800",
    icon: <IconCamera size={32} />,
  },
  {
    key: "tutors",
    category: t("solutions.tutors.title"),
    description: t("solutions.tutors.description"),
    price: "1,300",
    discounted: "1,000",
    icon: <IconBook size={32} />,
  },
  {
    key: "game_stores",
    category: t("solutions.game_stores.title"),
    description: t("solutions.game_stores.description"),
    price: "1,600",
    discounted: "1,300",
    icon: <IconGoGame size={32} />,
  },
  {
    key: "tech_startups",
    category: t("solutions.tech_startups.title"),
    description: t("solutions.tech_startups.description"),
    price: "2,500",
    discounted: "2,000",
    icon: <IconCpu size={32} />,
  },
  {
    key: "job_boards",
    category: t("solutions.job_boards.title"),
    description: t("solutions.job_boards.description"),
    price: "1,300",
    discounted: "1,000",
    icon: <IconBriefcase size={32} />,
  },
  {
    key: "blogs",
    category: t("solutions.blogs.title"),
    description: t("solutions.blogs.description"),
    price: "500",
    discounted: "400",
    icon: <IconNews size={32} />,
  },
];
// Export solutions if needed elsewhere
export { getSolutions };
